### ISSUE TITLE
Question of function 

### ISSUE THREAD

**Issue by vongohren** [kvasbo/inhabil.no#1]
Hey! I just want to ask how it works. You are calling an API, is this API the worker.js? I just don't see any registration of the service worker? Or do you have other code running? Because is this is the case it's just new to me 😅

**Comment by kvasbo** [comment]
It's linked up to Cloudflare Workers, which listens to the Git repo :) This is 100% of the code, the API is fully contained in worker.js.

**Comment by vongohren** [comment]
Ah cool! Have to check this out! Thanks for replying.
